### ISSUE TITLE
Pyglet flickering when rendering many objects

### ISSUE THREAD

**Issue by obiwac** [obiwac/python-minecraft-clone#10]
Title; when rendering many objects, Pyglet flickers for some reason. A call to `glFinish` at the end of the draw function _helps_, although it doesn't fix the flickering completely (I suspect it just makes it better as it adds a bit of delay in the drawing process).

**Comment by abhra2020-smart** [comment]
Try lowering the FPS.

**Comment by obiwac** [comment]
You certainly _will_ see the difference.

And that doesn't exactly solve the underlying issue 😛

**Comment by abhra2020-smart** [comment]
Well, I don't see any difference when _anything_ runs at 30 FPS. I'd think it's running as 'smooth as butter'.

**Comment by abhra2020-smart** [comment]
But, its **_your_** Minecraft clone, so your restrictions (I mean, your CPU or GPU will want to just about commit suicide anyway)

**Comment by abhra2020-smart** [comment]
Ok, you might wanna add chunk loading and unloading.

Check if the camera can see the chunk, if not, hide it,
Similar to what you did to the blocks in ep. 10

**Comment by obiwac** [comment]
You mean frustum culling?

Yeah, I will end up making a video on optimizations like that.

Still though, that doesn't solve the underlying issue. I'd like to know exactly why it's flickering, it's not enough to just work around it :smile:

**Comment by TNTMaster58** [comment]
To fix this issue, you can try to make it so that pyglet renders fewer objects. You can try to do this by rendering fewer vertices per block like only rendering vertices that the player can see and when a block is broken, then update vertices for the blocks around the block broken.

**Comment by obiwac** [comment]
That's already what I'm doing and that doesn't solve the underlying issue

**Comment by TNTMaster58** [comment]
I thinki have a solution for the problem. In main. py, change pyglet.clock.schedule_interval(self.update, 1.0 / 10000) to pyglet.clock.schedule(update)

**Comment by drakeerv** [comment]
That only seems to be an issue on linux.

**Comment by obiwac** [comment]
FreeBSD exhibits the same behaviour. Perhaps a bug in NVIDIA's Unix drivers?

**Comment by drakeerv** [comment]
Could possibly be Nvidia drivers then.

**Comment by Jukitsu** [comment]
My guess is that the framebuffer somehow doesn't clean up properly or buffers doesn't swap correctly. You could try glFlush(), glFinish() or set vsync to true

**Comment by Jukitsu** [comment]
I will think its rather because of buffer swapping is broken.

**Comment by obiwac** [comment]
I haven't actually encountered this problem since using aquaBSD's compositor, so I'm wondering if the non-use of a compositor was the issue. Closing this issue for now, I'll re-open it if anyone else reports this issue on a non-FreeBSD/Linux system or while using a compositor.
