### ISSUE TITLE
pyglet.gl.ContextException: Could not create GL context

### ISSUE THREAD

**Issue by MicrosoftwareStudios** [obiwac/python-minecraft-clone#101]
I am using a Raspberry Pi and running Pyglet 2.0.7, Python 3.9. When I run main.py, I am given the error "pyglet.gl.ContextException: Could not create GL context". I saw something saying that some apps may not work right with the new version of Pyglet. Thank you for your work, and, in advance, for your help.

**Comment by obiwac** [comment]
That's possible (@Jukitsu can you provide input on this?), but it could also be RPI-related as I haven't yet tested this on the Raspberry. Could you tell us if it's a VC4 or a VC6 Raspberry, as well as which drivers you're using?

**Comment by MicrosoftwareStudios** [comment]
I am not running any extra drivers except for the default ones, and I do not remember what VC# means.

**Comment by obiwac** [comment]
what model raspberry is it?

**Comment by MicrosoftwareStudios** [comment]
Raspberry Pi 4, Model B ARM64 Cortex CPU, 8 GB RAM.

**Comment by obiwac** [comment]
Closing this as stale.

**Comment by MicrosoftwareStudios** [comment]
I was able to fix the problem. Thanks!
