### ISSUE TITLE
funny question (gles related)

### ISSUE THREAD

**Issue by sinaSPOGames** [obiwac/python-minecraft-clone#103]
How can i make this work for opengl 2.1? :D

like... not even kidding

**Comment by obiwac** [comment]
are you talking about opengles 2.0 or desktop 2.1? and what for?

**Comment by sinaSPOGames** [comment]
> are you talking about opengles 2.0 or desktop 2.1? and what for?

sorry I forgot to reply lol nevermind I solved my issue by buying a new laptop
