### ISSUE TITLE
ImportError: DLL load failed while importing glm: The specified module could not be found.

### ISSUE THREAD

**Issue by Lilos2344** [obiwac/python-minecraft-clone#105]
i got this error Traceback (most recent call last):
  File "main.py", line 16, in <module>
    import shader
  File "C:\Users\Desktop\minecraft-python\shader.py", line 4, in <module>
    import glm
ImportError: DLL load failed while importing glm: The specified module could not be found.

------------------
(program exited with code: 1)

Press any key to continue . . .

Ps: i have installed pyglm.

**Comment by sinaSPOGames** [comment]
try to reinstall an older version the pluglm or whatever it's called it seems like the shader.py doesn't recognize that version

**Comment by obiwac** [comment]
how did you install pyglm?

**Comment by obiwac** [comment]
I am going to close this as this was opened a long time ago.
