### ISSUE TITLE
world gen update meshes

### ISSUE THREAD

**Issue by ajh123** [obiwac/python-minecraft-clone#14]
it takes alt least 7 seconds
mesured it like

in world.py
```
               import time

               ...

		Mtic = time.perf_counter()
		for chunk_position in self.chunks:
			self.chunks[chunk_position].update_mesh()
		Mtoc = time.perf_counter() 
                print(f"Time to generate meshes {Mtoc - Mtic:0.4f} seconds")
```

**Comment by obiwac** [comment]
Unfortunately, this isn't something that can easily be fixed in Python, owing to how slow it is.

Updating small regions of chunks is much faster as of the (yet to be released) 10th episode, however, and episode 11 will cover multithreading which should mostly mitigate the problem.

**Comment by ajh123** [comment]
when would we get world saving / loading

**Comment by obiwac** [comment]
Episode 11 likely

**Comment by Jukitsu** [comment]
Hello, I have been able to do some optimisation for chunk loading, but unfortunately it stays really slow (as of now I've only been able to increase chunk loading speed to around 2 chunks per second on my potato hardware) and it in general worsens framerate :/ you can check my fork at the ep11 optimised branch
