### ISSUE TITLE
Not loading on a computer with no GPU

### ISSUE THREAD

**Issue by drakeerv** [obiwac/python-minecraft-clone#4]
Here is the error:

line 36, in create_shader
    raise Shader_error(str(log_buffer.value))
shader.Shader_error: b''

The only gpu is the intel one built into the cpu

**Comment by obiwac** [comment]
Nvidia and AMD drivers are generally a bit more leniant when it comes to compiling shaders than Intel, so it's very possible that that's the problem. I'll have a look on my Intel machine tomorrow, thanks for posting the issue!

**Comment by drakeerv** [comment]
specs:
Intel(R) Xeon(R) CPU E3-1270 v5 @ 3.60 GHz
16 GB memory
1TB spinning drive

**Comment by drakeerv** [comment]
I got it to work, the error rasing system is bugged on this CPU, I took it out and it worked.
