### ISSUE TITLE
Game not starting. Says that GLSL is not supported

### ISSUE THREAD

**Issue by glowiak** [obiwac/python-minecraft-clone#55]
```
Traceback (most recent call last):
  File "main.py", line 204, in <module>
    game = Game()
  File "main.py", line 198, in __init__
    self.window = Window(config = self.config, width = 800, height = 600, caption = "Minecraft clone", resizable = True, vsync = False)
  File "main.py", line 34, in __init__
    self.shader = shader.Shader("vert.glsl", "frag.glsl")
  File "/usr/home/glowiak/gits/python-minecraft-clone/episode-12/shader.py", line 45, in __init__
    create_shader(self.vert_shader, vert_path)
  File "/usr/home/glowiak/gits/python-minecraft-clone/episode-12/shader.py", line 36, in create_shader
    raise Shader_error(str(log_buffer.value))
shader.Shader_error: b'0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES\n'
```

**Comment by obiwac** [comment]
Could I know what OS you're running on and what your graphics adapter is?

**Comment by glowiak** [comment]
My OS is FreeBSD 13.0-RELEASE-p4, my graphics adapter is intel integrated gpu. Minecraft 1.18 runs on about 100fps

**Comment by Jukitsu** [comment]
That's odd, if your GPU can run Mine raft (which uses GLSL 150, which is GL 3.2), how come it doesn't support GLSL 330 ? (Which is merely one version away)

**Comment by obiwac** [comment]
> my graphics adapter is intel integrated gpu

I need you to be a bit more specific than that.

Either way, I believe I know what the issue is, and it isn't really an "issue" per se, but rather just a simple incompatibility.

You can work around this by replacing `#version 330` in both shaders by the following:

```glsl
#version 300 es
precision mediump float;
```

This should convert your shaders to OpenGL ES shaders, which your drivers seems to support. I don't have the necessary hardware nearby to test this right now, so you might still get a few errors (in which case do send them).

**Comment by glowiak** [comment]
shader.Shader_error: b'0:2(1): preprocessor error: Illegal non-directive after #\n'

**Comment by obiwac** [comment]
Could you send your full shader source?

**Comment by glowiak** [comment]
Full shader source?

**Comment by drakeerv** [comment]
I think he means the whole shader file.

**Comment by glowiak** [comment]
vert.glsl:
"
#version 300 es
#percision mediump float;

layout(location = 0) in vec3 vertex_position;
layout(location = 1) in vec3 tex_coords;
layout(location = 2) in float shading_value;

out vec3 local_position;
out vec3 interpolated_tex_coords;
out float interpolated_shading_value;

uniform mat4 matrix;

void main(void) {
	local_position = vertex_position;
	interpolated_tex_coords = tex_coords;
	interpolated_shading_value = shading_value;
	gl_Position = matrix * vec4(vertex_position, 1.0);
}
"
frag.glsl:
"
#version 300 es
#precision mediump float;

out vec4 fragment_colour;

uniform sampler2DArray texture_array_sampler;

in vec3 local_position;
in vec3 interpolated_tex_coords;
in float interpolated_shading_value;

void main(void) {
	vec4 texture_colour = texture(texture_array_sampler, interpolated_tex_coords);
	fragment_colour = texture_colour * interpolated_shading_value;

	if (texture_colour.a == 0.0) { // discard if texel's alpha component is 0 (texel is transparent)
		discard;
	}
}
"

**Comment by obiwac** [comment]
You didn't copy the snipped I sent over correctly. `precision` isn't a directive which must be preceded with a `#`. Also, you've got a small typo in your vertex shader; you wrote `percision` instead of `precision`.

**Comment by glowiak** [comment]
Traceback (most recent call last):
  File "main.py", line 204, in <module>
    game = Game()
  File "main.py", line 198, in __init__
    self.window = Window(config = self.config, width = 800, height = 600, caption = "Minecraft clone", resizable = True, vsync = False)
  File "main.py", line 34, in __init__
    self.shader = shader.Shader("vert.glsl", "frag.glsl")
  File "/usr/home/glowiak/gits/python-minecraft-clone/episode-12/shader.py", line 51, in __init__
    create_shader(self.frag_shader, frag_path)
  File "/usr/home/glowiak/gits/python-minecraft-clone/episode-12/shader.py", line 36, in create_shader
    raise Shader_error(str(log_buffer.value))
shader.Shader_error: b"0:6(1): error: No precision specified in this scope for type `sampler2DArray'\n"

**Comment by glowiak** [comment]
Now this appears

**Comment by glowiak** [comment]
Thanks!!! Now everything works!

**Comment by drakeerv** [comment]
Why is this still pinned?

**Comment by obiwac** [comment]
Because it seems to be a relatively common issue.
