### ISSUE TITLE
Help needed in matrix.py!

### ISSUE THREAD

**Issue by NightTerror5293** [obiwac/python-minecraft-clone#62]
hello, i am having a problem in matrix.py,
![image](https://user-images.githubusercontent.com/88367912/155206957-fa5166db-3beb-4d3a-9236-0017eec4d8d6.png)
an error is being show in the lines 45,46,47
pls help me to resolve it

**Comment by obiwac** [comment]
Which version did you pull `matrix.py` from? The solution is likely quite trivial; just place `scale_x/y/z` with `x/y/z`.

**Comment by NightTerror5293** [comment]
I ran the file and i just got this as a result 
![image](https://user-images.githubusercontent.com/88367912/155565768-4336f80d-1def-4651-9d0d-7f80a0322721.png)

**Comment by obiwac** [comment]
> Which version did you pull `matrix.py` from?

Could you please answer this question?

**Comment by NightTerror5293** [comment]
2.0.1

**Comment by obiwac** [comment]
No I mean what episode

**Comment by NightTerror5293** [comment]
episode 4

**Comment by obiwac** [comment]
Ah. I'll take a look but it's a bit curious, since it works perfectly on my side.

**Comment by obiwac** [comment]
Closing this issue for now, if you're still getting a black screen, I think it'd be wiser to open up another issue :)

**Comment by abhra2020-smart** [comment]
this might be a git-side issue of the cloning and accidentally wrote the wrong version of the code there? im not sure tho
