### ISSUE TITLE
[suggestion] Import numbers imports python 3.10 numbers instead of numbers.py

### ISSUE THREAD

**Issue by drakeerv** [obiwac/python-minecraft-clone#63]
When I run ep5 it import the python 3.10+ numbers library instead of importing locally. I am using the unmodified code on windows 10. I have found a possible fix by creating a file called local.py and writing:
```py
from importlib.machinery import SourceFileLoader
import os

def local_import(library):
    return(SourceFileLoader("module.name", os.path.join(os.path.dirname(os.path.realpath(__file__)), (library if library.endswith(".py") else library + ".py"))).load_module())
```

and in block_type.py I change import numbers line to:
```py
import local
numbers = local.local_import("numbers")
```

**Comment by obiwac** [comment]
I guess there's not much we can do about this at this stage as new episodes don't have `numbers.py` anymore and either way the new file structure from EP13a onward avoids these kinds of issues.
