### ISSUE TITLE
Adding New Textures 

### ISSUE THREAD

**Issue by SharpColton** [obiwac/python-minecraft-clone#82]
Can someone help me understand how to add new texture for my coding class. Not understanding how to introduce a texture or block.

**Comment by obiwac** [comment]
Hey!

You can watch [episode 11](https://youtu.be/cWu-4ohrU1A) for details. The gist of it is that you're gonna want to add your texture to the `textures` directory, and then create a new block entry for your block in `data/blocks.mcpy`.

You can then use the block however you see fit, e.g. by setting the `self.holding` variable or some other way through the `set_block` function.

HTH!
