### ISSUE TITLE
water and lava are breakable

### ISSUE THREAD

**Issue by aniketm32012** [obiwac/python-minecraft-clone#87]
I know that, this game is a blocky game, but water and lava have characteristics like blocks and the can be broken. I want you to give them liquid properties and not solid properties to prevent players from breaking it.

**Comment by obiwac** [comment]
This is out of scope of the tutorial itself, but you're free to add that in `community`!

**Comment by aniketm32012** [comment]
Ok thanks, let me do some changes to the community.
