### ISSUE TITLE
A Lobby kinda thing.

### ISSUE THREAD

**Issue by aniketm32012** [obiwac/python-minecraft-clone#89]
I want you to add a "Lobby" (In case if it is not called Lobby, I am sorry because I don't know what is it called) like this - 
![image](https://user-images.githubusercontent.com/92517637/226596227-42c81343-1b2d-4e5b-afae-b5821598bb07.png)
Add the feature to generate world on it's own and save it and open the saved ones. I have noticed that your saved worlds never get updated.

**Comment by obiwac** [comment]
Already planned, but someone has already done something similar in a pending PR: #61

**Comment by aniketm32012** [comment]
Thanks
