### ISSUE TITLE
Window Sizing and rectangle not drawing issue

### ISSUE THREAD

**Issue by Kresan365** [obiwac/python-minecraft-clone#9]
I have just started following the tutorial  and I ran into this issue. I am copying the source code and the window is just making something else.

[main.zip](https://github.com/obiwac/python-minecraft-clone/files/5997078/main.zip)
![2021-02-17 (9)](https://user-images.githubusercontent.com/70752480/108234590-f2dd6600-716a-11eb-94c2-2d7b27d29e37.png)
![2021-02-17 (11)](https://user-images.githubusercontent.com/70752480/108234636-025caf00-716b-11eb-9f23-b0bea7a18e13.png)
 Here are the photos and codes

**Comment by obiwac** [comment]
Thanks for reporting the issue, I'll commit the fix and provide an explanation later today.

In the meantime, you can just add the argument `double_buffer = True` to your `gl.glConfig`.

**Comment by Kresan365** [comment]
Umm... where is the config file situated?

**Comment by obiwac** [comment]
Not a file. It's at the end of your `main.py` file.

**Comment by obiwac** [comment]
So quick explanation:

Taking a look at [`pyglet/window/__init__.py`](https://github.com/pyglet/pyglet/blob/b5482a/pyglet/window/__init__.py), we can see that the default `Config` sets the `double_buffer` argument:

```Python
if not config:
    for template_config in [gl.Config(double_buffer=True, depth_size=24, major_version=3, minor_version=3),
                            gl.Config(double_buffer=True, depth_size=16, major_version=3, minor_version=3),
                            None]:
        try:
            config = screen.get_best_config(template_config)
            break
        except NoSuchConfigException:
            pass
    if not config:
        raise NoSuchConfigException('No standard config is available.')
```

**But** `Config` does not enable `double_buffer` by default (which I don't think is very sensible but whatever). Intel's drivers seem to be picky about this, so it wasn't working.
